[build]
builder    = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand       = "/bin/sh /start.sh"
healthcheckPath    = "/api/accounts/health/"
healthcheckTimeout = 300
restartPolicyType  = "ON_FAILURE"
restartPolicyMaxRetries = 3
