# Generated by Django 5.2.12 on 2026-03-17 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsommationLigne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Montant dépensé')),
                ('piece_justificative', models.FileField(upload_to='justificatifs/%Y/%m/', verbose_name='Pièce justificative')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Note / description')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='budget.lignebudgetaire', verbose_name='Ligne budgétaire')),
            ],
            options={
                'verbose_name': 'Dépense enregistrée',
                'verbose_name_plural': 'Dépenses enregistrées',
                'db_table': 'consommation_ligne',
                'ordering': ['-date'],
            },
        ),
    ]
