# Generated by Django 5.2.12 on 2026-03-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_ajout_consommation_ligne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('CLOTURE', 'Clôturé'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=10, verbose_name='Statut'),
        ),
    ]
