# Generated by Django 5.2.12 on 2026-03-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_ajout_statut_brouillon'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='piece_justificative',
            field=models.FileField(blank=True, null=True, upload_to='budgets/pj/%Y/%m/', verbose_name='Pièce justificative de soumission'),
        ),
    ]
