# Generated by Django 5.2.12 on 2026-03-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_ajout_pj_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetannuel',
            name='annee_fin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année de fin'),
        ),
        migrations.AlterField(
            model_name='budgetannuel',
            name='annee',
            field=models.IntegerField(verbose_name='Année de début'),
        ),
    ]
