# Generated by Django 5.2.12 on 2026-03-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_ajout_annee_fin_budget_annuel'),
    ]

    def populate_budget_annuel(apps, schema_editor):
        Budget = apps.get_model('budget', 'Budget')
        for b in Budget.objects.select_related('allocation__budget_annuel').filter(allocation__isnull=False):
            b.budget_annuel = b.allocation.budget_annuel
            b.save(update_fields=['budget_annuel'])

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_annuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='budget.budgetannuel', verbose_name='Exercice budgétaire'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='budget.allocationdepartementale', verbose_name='Allocation départementale'),
        ),
        migrations.RunPython(populate_budget_annuel, migrations.RunPython.noop),
    ]
