# Generated by Django 5.2.12 on 2026-03-25 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_categorie_principale_sous_categorie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_notif', models.CharField(max_length=30, verbose_name='Type')),
                ('message', models.CharField(max_length=500, verbose_name='Message')),
                ('lien', models.CharField(blank=True, max_length=200, verbose_name='Lien')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to='justificatifs/%Y/%m/', verbose_name='Fichier')),
                ('nom', models.CharField(blank=True, max_length=200, verbose_name='Nom du fichier')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pièce justificative',
                'verbose_name_plural': 'Pièces justificatives',
                'db_table': 'piece_justificative',
                'ordering': ['date_ajout'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='categorieprincipale',
            name='unique_budget_cat_code',
        ),
        migrations.RemoveConstraint(
            model_name='souscategorie',
            name='unique_cat_sousc_code',
        ),
        migrations.AddField(
            model_name='budget',
            name='motif_rejet',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Motif de rejet'),
        ),
        migrations.AlterField(
            model_name='consommationligne',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='consommationligne',
            name='motif_rejet',
            field=models.CharField(blank=True, max_length=500, verbose_name='Motif de rejet'),
        ),
        migrations.AlterField(
            model_name='lignebudgetaire',
            name='libelle',
            field=models.CharField(max_length=200, verbose_name='Désignation'),
        ),
        migrations.AlterUniqueTogether(
            name='categorieprincipale',
            unique_together={('budget', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='souscategorie',
            unique_together={('categorie', 'code')},
        ),
        migrations.AddField(
            model_name='notification',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
        migrations.AddField(
            model_name='piecejustificative',
            name='depense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='budget.consommationligne', verbose_name='Dépense'),
        ),
    ]
