# Generated by Django 5.2.12 on 2026-03-16 16:18

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table', models.CharField(max_length=100, verbose_name='Table concernée')),
                ('enregistrement_id', models.CharField(max_length=40, verbose_name="ID de l'enregistrement")),
                ('valeur_avant', models.TextField(blank=True, null=True, verbose_name='Valeur avant')),
                ('valeur_apres', models.TextField(blank=True, null=True, verbose_name='Valeur après')),
                ('utilisateur_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('APPROVE', 'Approbation'), ('REJECT', 'Rejet'), ('SUBMIT', 'Soumission'), ('VIEW', 'Consultation'), ('EXPORT', 'Export')], max_length=20, verbose_name='Action')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Log Audit',
                'verbose_name_plural': 'Logs Audit',
                'db_table': 'log_audit',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['table', 'enregistrement_id'], name='log_audit_table_5fd659_idx'), models.Index(fields=['utilisateur', 'date_action'], name='log_audit_utilisa_9cc298_idx'), models.Index(fields=['action'], name='log_audit_action_7a43f8_idx'), models.Index(fields=['-date_action'], name='log_audit_date_ac_846dbe_idx')],
            },
        ),
    ]
